services:
  app:
    image: app:latest
    ports:
      - "127.0.0.1:8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    networks:
      - internal_network
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: "1.0"
  db:
    image: postgres:17.2-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crm
    hostname: database_host
    expose:
      - "5432"
    networks:
      - internal_network
    volumes:
      - db_data:/var/lib/postgres
networks:
  internal_network:

volumes:
  db_data:
